#ifndef _SQLITE3_CONFIG_H
#define _SQLITE3_CONFIG_H

#include<stdlib.h>

#define CAP_SIZE 32

#define SQLITE_THREADSAFE 0
#define SQLITE_DEFAULT_MEMSTATUS 0
#define SQLITE_USE_ALLOCA 1
#define HAVE_MALLOC_H 1
#define HAVE_MALLOC_USABLE_SIZE 1
#define SQLITE_ENABLE_MEMSYS5 1

#endif // _SQLITE3_CONFIG_H
